---

- name: TESTING NXOS_VTP_VERSION
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: PREPARING THE DEVICE DISABLING VTP
    nxos_command: command='no feature vtp ;' host={{ inventory_hostname }} type=config

  - name: ENSURE IT FAILS DUE TO FEATURE CURRENTLY NOT ENABLED
    nxos_vtp_password: vtp_password=ntc host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 1
    assert:
      that:
        - data | failed

  - name: PREPARING THE DEVICE ENABLING VTP
    nxos_command: command='feature vtp ;' host={{ inventory_hostname }} type=config

  - name: ENSURE IT FAILS DUE TO NO VTP DOMAIN EXISTING YET
    nxos_vtp_password: vtp_password=ntc host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 2
    assert:
      that:
        - data | failed

  - name: ENSURE IT FAILS DUE TO NO VTP DOMAIN EXISTING YET
    nxos_vtp_password: state=absent host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 3
    assert:
      that:
        - data | failed

  - name: PREPARING THE DEVICE CONFIGURING A VTP DOMAIN
    nxos_command: command='vtp domain ntc ;' host={{ inventory_hostname }} type=config

  - name: ENSURE VTP PASSWORD IS CONFIGURED
    nxos_vtp_password: vtp_password=ntc host={{ inventory_hostname }}
    register: data

  - name: TEST 4
    assert:
      that:
        - data.changed == true
        - data.end_state['vtp_password'] == 'ntc'

  - name: ENSURE VTP PASSWORD IS CHANGED
    nxos_vtp_password: vtp_password=new_ntc state=present host={{ inventory_hostname }}
    register: data

  - name: TEST 5
    assert:
      that:
        - data.changed == true
        - data.end_state['vtp_password'] == 'new_ntc'

  - name: ATTEMPT TO RECONFIGURE VTP PASSWORD
    nxos_vtp_password: vtp_password=new_ntc state=present host={{ inventory_hostname }}
    register: data

  - name: TEST 6
    assert:
      that:
        - data.changed == false
        - data.existing['vtp_password'] == 'new_ntc'

  - name: ENSURE VTP PASSWORD IS CASE-SENSIBLE
    nxos_vtp_password: vtp_password=NEW_NTC state=present host={{ inventory_hostname }}
    register: data

  - name: TEST 7
    assert:
      that:
        - data.changed == true
        - data.end_state['vtp_password'] == 'NEW_NTC'

  - name: ATTEMPT TO REMOVE WRONG VTP PASSWORD 
    nxos_vtp_password: vtp_password=new_ntc state=absent host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 8
    assert:
      that:
        - data | failed

  - name: ENSURE VTP PASSWORD IS REMOVED
    nxos_vtp_password: vtp_password=NEW_NTC state=absent host={{ inventory_hostname }}
    register: data

  - name: TEST 9
    assert:
      that:
        - data.changed == true
        - data.end_state['vtp_password'] == '\\'

  - name: ATTEMPT TO REMOVE WRONG VTP PASSWORD 
    nxos_vtp_password: state=absent host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 10
    assert:
      that:
        - data.changed == false
