---

- name: TESTING NXOS_VTP_VERSION
  hosts: n9k2
  connection: local
  gather_facts: no


  tasks:
  - name: PREPARING THE DEVICE DISABLING VTP
    nxos_command: command='no feature vtp ;' host={{ inventory_hostname }} type=config

  - name: ENSURE FAILS DUE TO FEATURE CURRENTLY NOT ENABLED
    nxos_vtp: domain=ntc state=present host={{ inventory_hostname }}
    register: data
    ignore_errors: true

  - name: TEST 1
    assert:
      that:
        - data | failed

  - name: PREPARING THE DEVICE ENABLING VTP
    nxos_command: command='feature vtp ;' host={{ inventory_hostname }} type=config

  - name: ENSURE VTP VERSION IS 2
    nxos_vtp_version: version=2 host={{ inventory_hostname }}
    register: data

  - name: TEST 2
    assert:
      that:
        - data.changed == true
        - data.end_state['version'] == '2'

  - name: ENSURE VTP VERSION IS CHANGED TO 1
    nxos_vtp_version: version=1 host={{ inventory_hostname }}
    register: data

  - name: TEST 3
    assert:
      that:
        - data.changed == true
        - data.end_state['version'] == '1'

  - name: ATTEMPT TO RECONFIGURE VTP VERSION TO 1
    nxos_vtp_version: version=1 host={{ inventory_hostname }}
    register: data

  - name: TEST 4
    assert:
      that:
        - data.changed == false
        - data.existing['version'] == '1'
